server.port=8096
rabis.openapi.schema.url=http://localhost:8088
rabis.openapi.username=admin
rabis.openapi.password=admin

rabis.data.provider.url=http://localhost:8091

spring.servlet.multipart.max-file-size=-1
spring.servlet.multipart.max-request-size=-1


route_url=${route_prefix_url:}
springdoc.api-docs.path=${route_url}/api-docs
springdoc.swagger-ui.path=${route_url}/swagger-ui